(function(t,u){function l(a,c){if(null==c)return null;null==c.__id__&&(c.__id__=v++);var b;null==a.hx__closures__?a.hx__closures__={}:b=a.hx__closures__[c.__id__];null==b&&(b=function(){return b.method.apply(b.scope,arguments)},b.scope=a,b.method=c,a.hx__closures__[c.__id__]=b);return b}var f=function(a,c){null==c&&(c=1);this.canvas=a;this.quality=c;this.surface={centerX:0,centerY:0,width:1,height:1,isPanning:!1,isZooming:!1,lastX:0,lastY:0};this.parameters={startTime:new Date,time:0,mouseX:.5,mouseY:.5,
screenWidth:0,screenHeight:0};this.gl=n.getContextWebGL(a,{preserveDrawingBuffer:!0});this.buffer=this.gl.createBuffer();this.gl.bindBuffer(34962,this.buffer);this.gl.bufferData(34962,new Float32Array([-1,-1,1,-1,-1,1,1,-1,1,1,-1,1]),35044);this.surface.buffer=this.gl.createBuffer();this.parameters.screenWidth=a.width;this.parameters.screenHeight=a.height;null!=this.gl&&(this.gl.viewport(0,0,a.width,a.height),this.createRenderTargets());this.compileScreenProgram()};f.__name__=["FragmentShaderView"];
f.prototype={resize:function(a,c){this.canvas.width=a/this.quality|0;this.canvas.height=c/this.quality|0;this.canvas.style.width=a+"px";this.canvas.style.height=c+"px";this.parameters.screenWidth=this.canvas.width;this.parameters.screenHeight=this.canvas.height;this.computeSurfaceCorners();null!=this.gl&&(this.gl.viewport(0,0,this.canvas.width,this.canvas.height),this.createRenderTargets())},compile:function(a,c){null==c&&(c=f.defaultSurfaceVertexShaderSource);var b=this.gl.createProgram(),e=this.createShader(c,
35633),k=this.createShader(a,35632);null!=e&&null!=k&&(this.gl.attachShader(b,e),this.gl.attachShader(b,k),this.gl.deleteShader(e),this.gl.deleteShader(k),this.gl.linkProgram(b),null==this.gl.getProgramParameter(b,35714)?(window.console.error(this.gl.getProgramInfoLog(b)),window.console.error("VALIDATE_STATUS: "+m.string(this.gl.getProgramParameter(b,35715)),"ERROR: "+this.gl.getError())):(null!=this.currentProgram&&this.gl.deleteProgram(this.currentProgram),this.currentProgram=b,this.cacheUniformLocation(b,
"time"),this.cacheUniformLocation(b,"mouse"),this.cacheUniformLocation(b,"resolution"),this.cacheUniformLocation(b,"backbuffer"),this.cacheUniformLocation(b,"surfaceSize"),this.gl.useProgram(this.currentProgram),this.surface.positionAttribute=this.gl.getAttribLocation(this.currentProgram,"surfacePosAttrib"),this.vertexPosition=this.gl.getAttribLocation(this.currentProgram,"position"),this.gl.enableVertexAttribArray(this.vertexPosition)))},render:function(){if(null!=this.currentProgram){var a=(new Date).getTime();
this.parameters.time=a-this.parameters.startTime;this.gl.useProgram(this.currentProgram);this.gl.uniform1f(this.currentProgram.uniformsCache.time,this.parameters.time/1E3);this.gl.uniform2f(this.currentProgram.uniformsCache.mouse,this.parameters.mouseX,this.parameters.mouseY);this.gl.uniform2f(this.currentProgram.uniformsCache.resolution,this.parameters.screenWidth,this.parameters.screenHeight);this.gl.uniform1i(this.currentProgram.uniformsCache.backbuffer,0);this.gl.uniform2f(this.currentProgram.uniformsCache.surfaceSize,
this.surface.width,this.surface.height);this.gl.bindBuffer(34962,this.surface.buffer);this.gl.bindBuffer(34962,this.buffer);this.gl.vertexAttribPointer(this.vertexPosition,2,5126,!1,0,0);this.gl.activeTexture(33984);this.gl.bindTexture(3553,this.backTarget.texture);this.gl.bindFramebuffer(36160,this.frontTarget.framebuffer);this.gl.clear(16640);this.gl.drawArrays(4,0,6);this.gl.useProgram(this.screenProgram);this.gl.uniform2f(this.screenProgram.uniformsCache.resolution,this.parameters.screenWidth,
this.parameters.screenHeight);this.gl.uniform1i(this.screenProgram.uniformsCache.texture,1);this.gl.bindBuffer(34962,this.buffer);this.gl.vertexAttribPointer(this.screenVertexPosition,2,5126,!1,0,0);this.gl.activeTexture(33985);this.gl.bindTexture(3553,this.frontTarget.texture);this.gl.bindFramebuffer(36160,null);this.gl.clear(16640);this.gl.drawArrays(4,0,6);a=this.frontTarget;this.frontTarget=this.backTarget;this.backTarget=a}},dispose:function(){this.currentProgram=null},createShader:function(a,
c){var b=this.gl.createShader(c),e=0,k;this.gl.shaderSource(b,a);this.gl.compileShader(b);if(!this.gl.getShaderParameter(b,35713)){for(var d=this.gl.getShaderInfoLog(b);1<d.length&&32>h.cca(d,d.length-1);)d=d.substring(0,d.length-1);for(window.console.error(d);0<=e;){e=d.indexOf("ERROR: 0:",e);if(0>e)break;e+=9;k=d.indexOf(":",e);k>e&&(b=m.parseInt(d.substring(e,k)),!isNaN(b)&&0<b&&(e=k+1,d.indexOf("ERROR: 0:",e)))}return null}return b},compileScreenProgram:function(){if(null!=this.gl){var a=this.gl.createProgram(),
c=this.createShader(f.screenVertexShaderSource,35633),b=this.createShader(f.screenFragmentShaderSource,35632);this.gl.attachShader(a,c);this.gl.attachShader(a,b);this.gl.deleteShader(c);this.gl.deleteShader(b);this.gl.linkProgram(a);this.gl.getProgramParameter(a,35714)?(this.screenProgram=a,this.gl.useProgram(this.screenProgram),this.cacheUniformLocation(a,"resolution"),this.cacheUniformLocation(a,"texture"),this.screenVertexPosition=this.gl.getAttribLocation(this.screenProgram,"position"),this.gl.enableVertexAttribArray(this.screenVertexPosition)):
window.console.error("VALIDATE_STATUS: "+m.string(this.gl.getProgramParameter(a,35715)),"ERROR: "+this.gl.getError())}},cacheUniformLocation:function(a,c){null==a.uniformsCache&&(a.uniformsCache={});a.uniformsCache[c]=this.gl.getUniformLocation(a,c)},computeSurfaceCorners:function(){if(null!=this.gl){this.surface.width=this.surface.height*this.parameters.screenWidth/this.parameters.screenHeight;var a=.5*this.surface.width,c=.5*this.surface.height;this.gl.bindBuffer(34962,this.surface.buffer);this.gl.bufferData(34962,
new Float32Array([this.surface.centerX-a,this.surface.centerY-c,this.surface.centerX+a,this.surface.centerY-c,this.surface.centerX-a,this.surface.centerY+c,this.surface.centerX+a,this.surface.centerY-c,this.surface.centerX+a,this.surface.centerY+c,this.surface.centerX-a,this.surface.centerY+c]),35044)}},createTarget:function(a,c){var b={};b.framebuffer=this.gl.createFramebuffer();b.renderbuffer=this.gl.createRenderbuffer();b.texture=this.gl.createTexture();this.gl.bindTexture(3553,b.texture);this.gl.texImage2D(3553,
0,6408,a,c,0,6408,5121,null);this.gl.texParameteri(3553,10242,33071);this.gl.texParameteri(3553,10243,33071);this.gl.texParameteri(3553,10240,9728);this.gl.texParameteri(3553,10241,9728);this.gl.bindFramebuffer(36160,b.framebuffer);this.gl.framebufferTexture2D(36160,36064,3553,b.texture,0);this.gl.bindRenderbuffer(36161,b.renderbuffer);this.gl.renderbufferStorage(36161,33189,a,c);this.gl.framebufferRenderbuffer(36160,36096,36161,b.renderbuffer);this.gl.bindTexture(3553,null);this.gl.bindRenderbuffer(36161,
null);this.gl.bindFramebuffer(36160,null);return b},createRenderTargets:function(){this.frontTarget=this.createTarget(this.parameters.screenWidth,this.parameters.screenHeight);this.backTarget=this.createTarget(this.parameters.screenWidth,this.parameters.screenHeight)},__class__:f};var h=function(){};h.__name__=["HxOverrides"];h.cca=function(a,c){var b=a.charCodeAt(c);return b!=b?void 0:b};h.substr=function(a,c,b){if(null==b)b=a.length;else if(0>b)if(0==c)b=a.length+b;else return"";return a.substr(c,
b)};Math.__name__=["Math"];var d=t.ShaderPreview=function(a){var c=this;f.call(this,window.document.createElement("canvas"),atom.config.get("shaderpreview.quality"));this.file=new w(a.path);this.element=window.document.createElement("div");this.element.classList.add("shaderpreview");this.element.appendChild(this.canvas);this.fileChangeListener=this.file.onDidChange(l(this,this.handleSourceFileChange));this.file.read(!0).then(function(a){try{c.compile(a)}catch(e){atom.notifications.addWarning(e)}});
this.element.addEventListener("click",function(){null==c.animationFrameId?c.animationFrameId=window.requestAnimationFrame(l(c,c.update)):null!=c.animationFrameId&&(window.cancelAnimationFrame(c.animationFrameId),c.animationFrameId=null)},!1);this.animationFrameId=window.requestAnimationFrame(l(this,this.update))};d.__name__=["ShaderPreview"];d.activate=function(a){d.disposables=new x;d.disposables.add(atom.workspace.addOpener(d.openURI));d.disposables.add(atom.commands.add("atom-workspace","shaderpreview:preview",
function(a){a=a.target.getAttribute("data-path");p.exists(a)&&atom.workspace.open("shaderpreview://"+a)}));atom.workspace.onDidDestroyPaneItem(function(a){try{var b=a.item;"ShaderPreview"==q.getClassName(null==b?null:g.getClass(b))&&a.item.dispose()}catch(e){}})};d.deactivate=function(){d.disposables.dispose()};d.openURI=function(a){return r.startsWith(a,"shaderpreview://")?new d({path:h.substr(a,16,null)}):null};d.deserialize=function(a){return new d(a)};d.__super__=f;d.prototype=function(a,c){function b(){}
b.prototype=a;var e=new b,d;for(d in c)e[d]=c[d];c.toString!==Object.prototype.toString&&(e.toString=c.toString);return e}(f.prototype,{serialize:function(){return{deserializer:"ShaderPreview",path:this.file.getPath()}},dispose:function(){f.prototype.dispose.call(this);this.fileChangeListener.dispose()},getPath:function(){return this.file.getPath()},getIconName:function(){return"git-branch"},getTitle:function(){return this.file.getBaseName()},getURI:function(){var a=this.file.getPath();return"file://"+
encodeURIComponent(a)},update:function(a){this.animationFrameId=window.requestAnimationFrame(l(this,this.update));this.element.offsetWidth==this.canvas.width&&this.element.offsetHeight==this.canvas.height||this.resize(this.element.offsetWidth,this.element.offsetHeight);this.render()},toggleAnimationFrame:function(){null==this.animationFrameId?this.animationFrameId=window.requestAnimationFrame(l(this,this.update)):null!=this.animationFrameId&&(window.cancelAnimationFrame(this.animationFrameId),this.animationFrameId=
null)},requestAnimationFrame:function(){this.animationFrameId=window.requestAnimationFrame(l(this,this.update))},cancelAnimationFrame:function(){null!=this.animationFrameId&&(window.cancelAnimationFrame(this.animationFrameId),this.animationFrameId=null)},handleSourceFileChange:function(){var a=this;this.file.read(!0).then(function(c){a.compile(c)})},handleClick:function(a){null==this.animationFrameId?this.animationFrameId=window.requestAnimationFrame(l(this,this.update)):null!=this.animationFrameId&&
(window.cancelAnimationFrame(this.animationFrameId),this.animationFrameId=null)},__class__:d});var m=function(){};m.__name__=["Std"];m.string=function(a){return g.__string_rec(a,"")};m.parseInt=function(a){var c=parseInt(a,10);0!=c||120!=h.cca(a,1)&&88!=h.cca(a,1)||(c=parseInt(a));return isNaN(c)?null:c};var r=function(){};r.__name__=["StringTools"];r.startsWith=function(a,c){return a.length>=c.length?h.substr(a,0,c.length)==c:!1};var q=function(){};q.__name__=["Type"];q.getClassName=function(a){a=
a.__name__;return null==a?null:a.join(".")};var x=require("atom").CompositeDisposable,w=require("atom").File,g=function(){};g.__name__=["js","Boot"];g.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var c=a.__class__;if(null!=c)return c;a=g.__nativeClassName(a);return null!=a?g.__resolveNativeClass(a):null};g.__string_rec=function(a,c){if(null==a)return"null";if(5<=c.length)return"<...>";var b=typeof a;"function"==b&&(a.__name__||a.__ename__)&&(b="object");switch(b){case "function":return"<function>";
case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];b=a[0]+"(";c+="\t";for(var e=2,d=a.length;e<d;)var f=e++,b=2!=f?b+(","+g.__string_rec(a[f],c)):b+g.__string_rec(a[f],c);return b+")"}b=a.length;e="[";c+="\t";for(d=0;d<b;)f=d++,e+=(0<f?",":"")+g.__string_rec(a[f],c);return e+"]"}try{e=a.toString}catch(h){return"???"}if(null!=e&&e!=Object.toString&&"function"==typeof e&&(b=a.toString(),"[object Object]"!=b))return b;b=null;e="{\n";c+="\t";d=null!=a.hasOwnProperty;for(b in a)d&&
!a.hasOwnProperty(b)||"prototype"==b||"__class__"==b||"__super__"==b||"__interfaces__"==b||"__properties__"==b||(2!=e.length&&(e+=", \n"),e+=c+b+" : "+g.__string_rec(a[b],c));c=c.substring(1);return e+("\n"+c+"}");case "string":return a;default:return String(a)}};g.__nativeClassName=function(a){a=g.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};g.__resolveNativeClass=function(a){return u[a]};var n=function(){};n.__name__=["js","html","_CanvasElement","CanvasUtil"];
n.getContextWebGL=function(a,c){for(var b=0,e=["webgl","experimental-webgl"];b<e.length;){var d=e[b];++b;d=a.getContext(d,c);if(null!=d)return d}return null};var y=require("fs");require("buffer");var p=function(){};p.__name__=["sys","FileSystem"];p.exists=function(a){try{return y.accessSync(a),!0}catch(c){return!1}};var v=0;module.exports=d;String.prototype.__class__=String;String.__name__=["String"];Array.__name__=["Array"];Date.prototype.__class__=Date;Date.__name__=["Date"];f.screenVertexShaderSource=
"\n        attribute vec3 position;\n        void main() {\n            gl_Position = vec4( position, 1.0 );\n        }";f.screenFragmentShaderSource="\n        precision mediump float;\n        uniform vec2 resolution;\n        uniform sampler2D texture;\n        void main() {\n            vec2 uv = gl_FragCoord.xy / resolution.xy;\n            gl_FragColor = texture2D( texture, uv );\n        }";f.defaultSurfaceVertexShaderSource="\n        attribute vec3 position;\n        attribute vec2 surfacePosAttrib;\n        varying vec2 surfacePosition;\n        void main() {\n            surfacePosition = surfacePosAttrib;\n            gl_Position = vec4( position, 1.0 );\n        }";
d.NAME="shaderpreview";d.PREFIX="shaderpreview://";d.allowedFileTypes=["frag"];g.__toStr={}.toString})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this,"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
